### ISSUE TITLE
Не запускается

### ISSUE THREAD

**Issue by steelswing** [Ferius057/VK-MailingGroup#8]
Нажимаю кнопку запустить, а оно не запускается, что делать?

**Comment by Ferius057** [comment]
Прочтите [Использование](https://github.com/Ferius057/VK-MailingGroup/blob/master/README.md#%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)

Или напишите мне в [vk](http://vk.me/ferius_057) или [tg](http://ferius_057.t.me)

**Comment by steelswing** [comment]
скинь тг

**Comment by steelswing** [comment]
скинь тг

**Comment by steelswing** [comment]
скинь тг

**Comment by steelswing** [comment]
скинь тг

**Comment by steelswing** [comment]
скинь тг

**Comment by steelswing** [comment]
@all скинь тг

**Comment by steelswing** [comment]
@java
